### ISSUE TITLE
Custom YARA rule file is not included

### ISSUE THREAD

**Issue by anotherbridge** [michelcrypt4d4mus/pdfalyzer#10]
When trying to add custom YARA rules via the `--yara-file` or `-Y` argument does not seem to have an effect. The tool still contains the same output as without providing a valid YARA rule file. The YARA output also does not include the rule file. It only includes the three default rule files that are shipped with the tool.

**Comment by michelcrypt4d4mus** [comment]
Fix released as 1.14.6
