### ISSUE TITLE
The output `.txt` file contains garbled codes.

### ISSUE THREAD

**Issue by scillidan** [michelcrypt4d4mus/pdfalyzer#11]
OS: Windons10

The option `-html`, `-svg` have no problem. But the `.txt ` have garbled codes, liked errors about ascii character🤔:

```
<0x1b>[7m╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮<0x1b>[0m
<0x1b>[7m│<0x1b>[0m<0x1b>[7m                                                                                                                                                           <0x1b>[0m<0x1b>[7m│<0x1b>[0m
<0x1b>[7m│<0x1b>[0m<0x1b>[7m <0x1b>[0m<0x1b>[7mYARA Scan of PDF rules for 'The.pdf'<0x1b>[0m<0x1b>[7m                                                                                           <0x1b>[0m<0x1b>[7m <0x1b>[0m<0x1b>[7m│<0x1b>[0m
<0x1b>[7m│<0x1b>[0m<0x1b>[7m                                                                                                                                                           <0x1b>[0m<0x1b>[7m│<0x1b>[0m
<0x1b>[7m╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯<0x1b>[0m
```

It's just a little unimportant problem. Thanks for read :)

**Comment by michelcrypt4d4mus** [comment]
Thanks for the bug report. It looks like it's trying to write colored ascii and something is going wrong. My guess is it's related to the difference between Windows and *nix platforms.

**Comment by michelcrypt4d4mus** [comment]
under the hood this is just a call to [`console.save_text()` from the rich text package](https://rich.readthedocs.io/en/stable/reference/console.html#rich.console.Console.save_text). is it possible your terminal is somehow configured in a weird way?

**Comment by scillidan** [comment]
I run `python pdfalyzer.py -t input.pdf -o D:\home` in `cmd.exe`. It does work very well.

![image](https://github.com/michelcrypt4d4mus/pdfalyzer/assets/19889610/103d38ee-14a7-4114-b279-d0d4cb5b022f)

Thank you for reminding! I find that it's my fault :P

I used command rudely with `pdfalyze.exe -t input.pdf > output.txt`.
