### ISSUE TITLE
1.14.5 did not get marked as latest release

### ISSUE THREAD

**Issue by chenrui333** [michelcrypt4d4mus/pdfalyzer#13]
👋 it looks like 0.14.5 did not get marked as latest release. 

relates to https://github.com/Homebrew/homebrew-core/pull/154431

**Comment by michelcrypt4d4mus** [comment]
is that an issue given that i released 1.14.6 already? happy to do whatever is needed to resolve but not sure how to proceed...

**Comment by michelcrypt4d4mus** [comment]
i made a release for 1.14.5: https://github.com/michelcrypt4d4mus/pdfalyzer/releases/tag/v1.14.5

**Comment by chenrui333** [comment]
yeah, I was mostly asking about the release semantics, I am happy with a newer version. Thanks! 🚢

**Comment by michelcrypt4d4mus** [comment]
would usually mark a new release as latest but immediately after releasing 1.14.5 i noticed a lonely bug filed by @anotherbridge months ago that seemed important to fix quickly.

**Comment by chenrui333** [comment]
sounds reasonable. you should probably also setup some github action pipeline as well :)

**Comment by michelcrypt4d4mus** [comment]
i have a local script that handles tagging / updating CHANGELOG / publishing to pypi... only step that is manual is the GH release and i'm too lazy to set that up lol
