### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by Zeldapedia** [michelcrypt4d4mus/pdfalyzer#14]
I am getting this error when trying to run a basic pdfalyzer command:

```
Traceback (most recent call last):
  File "/pdfalyzer/pdfalyzer.py", line 16, in <module>
    from yaralyzer.output.file_hashes_table import compute_file_hashes
ModuleNotFoundError: No module named 'yaralyzer.output.file_hashes_table'
```

For context, I have all the dependencies (as specified in the requirements.txt file) installed via pip in a conda environment. I have a clone of this repository on my Desktop, and when I attempt to run the pdfalyzer python script located in /pdfalyzer/ from within the conda context, this is the error I get. And I made sure that yaralyzer was installed correctly; I did a "yaralyze --version" command and got 0.7.1 as the output. Maybe its because I didn't use pipx, but I like using Conda, and pipx isn't available on Conda

**Comment by michelcrypt4d4mus** [comment]
it's failing [here](https://github.com/michelcrypt4d4mus/pdfalyzer/blob/master/pdfalyzer/pdfalyzer.py#L16), on the first line it's trying to import yaralyzer... so whatever environment you are running in doesn't have the yaralyzer package. unfortunately i have 0 experience with conda other than to say conda and pipx are pretty orthogonal and should not conflict or interact with each other in any way. unless you are trying to use pdfalyzer as a package or do development on it you should try to install with pipx (or homebrew if you are on a mac - someone published pdfalyzer as a hombrew package).

**Comment by michelcrypt4d4mus** [comment]
...but if you figure out why it failed to install correctly with conda (and maybe even submit a PR to fix it) i'd love to hear about it. it seems to me like conda installed yaralzyer as an executable script but _not_ as a library.

**Comment by michelcrypt4d4mus** [comment]
actually... i know what your issue is. you're using `requirements.txt` but that is not how dependencies are managed any more in this repo; they are managed by `pyproject.toml`. i deleted the file.

installing via `pyproject.toml` will almost certainly fix your issue as `requirements.txt` was pointing to an old version of yaralyzer.
